USE concurrency;
-- SET SESSION TRANSACTION ISOLATION LEVEL REPEATABLE READ;
SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED;

START TRANSACTION;

SELECT	* 
FROM	Employee
WHERE	Lastname Like 'A%';

SELECT SLEEP(10);

SELECT	* 
FROM 	Employee
WHERE	Lastname Like 'A%'; 

COMMIT

