USE concurrency;
SET SQL_SAFE_UPDATES = 0;
-- SET SESSION TRANSACTION ISOLATION LEVEL REPEATABLE READ;
SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED;

START TRANSACTION;

SELECT SLEEP(5);

UPDATE	Employee
SET  	Salary = Salary + 1000
WHERE	WorkDept = 'D11';

COMMIT;
SET SQL_SAFE_UPDATES = 1;