-- 2nd Transaction -- 
USE concurrency;
-- SET SESSION TRANSACTION ISOLATION LEVEL SERIALIZABLE;
SET SESSION TRANSACTION ISOLATION LEVEL REPEATABLE READ;

START TRANSACTION; 

SELECT	* 
FROM	Employee
WHERE	WorkDept = 'D11';

SELECT SLEEP(10);

SELECT	* 
FROM	Employee
WHERE	Salary > 5000
