-- 1st Transaction -- 
USE concurrency;
-- SET SESSION TRANSACTION ISOLATION LEVEL SERIALIZABLE;
SET SESSION TRANSACTION ISOLATION LEVEL REPEATABLE READ;

START TRANSACTION; 

SELECT SLEEP(5);

INSERT INTO Employee
VALUES ( '000123', 'Sheldon', 'Q', 'Jetstream', 'D11', '7777', '05/01/00', 520000.00);

COMMIT;